# Generated by Django 3.2.8 on 2021-11-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tejido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.IntegerField()),
                ('color', models.IntegerField()),
                ('inflammation', models.IntegerField()),
            ],
        ),
    ]
